### ISSUE TITLE
Set actual data directory

### ISSUE THREAD

**Issue by colindaven** [galaxyproject/ansible-cvmfs#37]
Hi Galaxy Admins,

just checking - we are serving from a small VM (14G in / ) so want to set the Reference data to be saved on a NAS.

Is it sufficient to just change this setting from `/srv` to our `/bignfs/cvmfs` ?

https://github.com/galaxyproject/ansible-cvmfs/blob/main/defaults/main.yml

`cvmfs_srv_mount: /srv`

Thanks !

**Comment by hexylena** [comment]
Hi @colindaven I take it you're setting up a stratum1? That should be sufficient then!

**Comment by colindaven** [comment]
Hi @hexylena thanks for the quick response. Excellent, we'll try that out. I think we're creating an internal stratum1 ...... having briefly read the cvmfs docs, I'm not so sure.
