### ISSUE TITLE
/etc/cvmfs/repositories.d directory doesn't exist on cvmfs_role of "client". Ansible fails on options.yml

### ISSUE THREAD

**Issue by deano2point0** [galaxyproject/ansible-cvmfs#38]
When running this role on a node with cvmfs_role of "client" it fails when it gets to the lineinfile module in options.yml as there is no /etc/cvmfs/repositories.d directory or contents on the node. I have read through the tasks file and I can't see anything that would create these files on a client. Am I missing something, or is this broken?

**Comment by hexylena** [comment]
What OS are you using? We hadn't seen this error before and a lot of us are using this role in client mode.

**Comment by deano2point0** [comment]
The client I am running this on is CentOS 7.

**Comment by deano2point0** [comment]
The play I'm using is based on the one given in the examples in the readme for creating your own infrastructure. I have replaced all the variables (domain URLs etc ) with the values for my environment - added the keys that were created on the first run - set hosts to all. Stratum0 server built fine and works, just the client failing as described.  

`- name: CVMFS
  hosts: cvmfsstratum0servers
  vars:
    cvmfs_numfiles: 4096
    cvmfs_server_urls:
      - domain: example.org
        urls:
          - "http://cvmfs0.example.org/cvmfs/@fqrn@"
    cvmfs_repositories:
      - repository: foo.example.org
        stratum0: cvmfs0.example.org
        key_dir: /etc/cvmfs/keys/example.org
        server_options:
          - CVMFS_AUTO_TAG=false
          - CVMFS_GARBAGE_COLLECTION=true
          - CVMFS_AUTO_GC=false
        client_options:
          - CVMFS_NFILES=4096
      - repository: bar.example.org
        stratum0: cvmfs0.example.org
        key_dir: /etc/cvmfs/keys/example.org
  roles:
    - galaxyproject.cvmfs`

**Comment by hexylena** [comment]
maybe @natefoo has some input here, I'm going into summer holidays for the next month sorry.

**Comment by deano2point0** [comment]
No problem, have a nice Holiday!

**Comment by natefoo** [comment]
Is `/etc/cvmfs` created at all? It should either be when the `cvmfs-config-default` package is installed or when `cvmfs_config setup` runs [here](https://github.com/galaxyproject/ansible-cvmfs/blob/main/tasks/client.yml#L24).

**Comment by deano2point0** [comment]
Hi, Yes /etc/cvmfs exists, but there is no 'repositories.d' directory inside it.
